version: "3"

services:
  node:
    build:
      context: .
    volumes:
      - "./:/src/app"
    ports:
      - "3000:3000"
    links:
      - mongodb

  test:
    build:
      context: .
    volumes:
      - "./:/src/app"
    environment:
      - DB_NAME=mercury-test
    command: npm run docker-test
    links:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
